routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', 'GuestController@index');
Route::get('books/{book}/borrow', [
    'middleware' => ['auth', 'role:member'],
    'as'=> 'guest.books.borrow',
    'uses'=> 'BooksController@borrow'
    ]);

    Route::put('books/{book}/return', [
        'middleware' => ['auth', 'role:member'],
        'as'=> 'member.books.return',
        'uses' => 'BooksController@returnBack'
        ]);

        Route::get('auth/verify/{token}', 'Auth\RegisterController@verify');
        Route::get('auth/send-verification', 'Auth\RegisterController@sendVerification');
        Route::get('settings/profile', 'SettingsController@profile');

        Route::get('settings/profile/edit', 'SettingsController@editProfile');
        Route::post('settings/profile', 'SettingsController@updateProfile');
        Route::get('settings/password', 'SettingsController@editPassword');
        Route::post('settings/password', 'SettingsController@updatePassword');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::group(['prefix'=>'admin', 'middleware'=>['auth']], function () {
    Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {
    Route::resource('authors', 'AuthorsController');
    Route::resource('books', 'BooksController');
    Route::resource('members', 'MembersController');
    Route::get('statistics', [
        'as'=>'statistics.index',
        'uses'=>'StatisticsController@index'
        ]);
        Route::get('export/books', [
            'as' => 'export.books',
            'uses' => 'BooksController@export'
            ]);
            Route::post('export/books', [
            'as'=> 'export.books.post',
            'uses' => 'BooksController@exportPost'
            ]);
            Route::get('template/books', [
                'as' => 'template.books',
                'uses' => 'BooksController@generateExcelTemplate'
                ]);
                Route::post('import/books', [
                'as'=> 'import.books',
                'uses' => 'BooksController@importExcel'
                ]);
});

resources/views/layouts/_flash.blade.php
@if (session()->has('flash_notification.message'))
<div class="container">
<div class="alert alert-{{ session()->get('flash_notification.level') }}">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
{!! session()->get('flash_notification.message') !!}
</div>
</div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->


    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    {{--  <link rel="shortcut icon" href="{{ asset('img/ico.png') }}" />  --}}
    <!-- Styles -->

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/selectize.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet">
    <link href="{{ asset('css/selectize.bootstrap3.css') }}" rel="stylesheet">
    <link href="{{ asset('css/jquery.dataTables.css') }}" rel="stylesheet">
    <link href="{{ asset('css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    {{--  <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">  --}}

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @if (Auth::check())
                            <li class="nav-item {{ Request::is('home') ? 'active ' : '' }}">
                                <a class="nav-link" href="{{ url('/home') }}">Dashboard</a>
                            </li>
                            @role('admin')
                            <li class="nav-item {{ Request::is('admin/authors') ? 'active ' : '' }}">
                                <a class="nav-link" href="{{ route('authors.index') }}">Penulis</a>
                            </li>
                            <li class="nav-item {{ Request::is('admin/books') ? 'active ' : '' }}">
                                <a class="nav-link" href="{{ route('books.index') }}">Buku</a>
                            </li>
                            <li class="nav-item {{ Request::is('admin/members') ? 'active ' : '' }}">
                                <a class="nav-link" href="{{ route('members.index') }}">Member</a>
                            </li>
                            <li class="nav-item {{ Request::is('admin/statistics') ? 'active ' : '' }}">
                                <a class="nav-link" href="{{ route('statistics.index') }}">Peminjaman</a>
                            </li>
                            @endrole
                            @if (auth()->check())
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url('/settings/profile') }}">Profil</a
                            </li>
                            @endif
                            {{--  <li class="nav-item {{ Request::is('admin/books') ? 'active ' : '' }}">
                                <a class="nav-link" href="{{ route('books.index') }}">Buku</a>
                            </li>
                            <li class="nav-item {{ Request::is('admin/members') ? 'active ' : '' }}">
                                <a class="nav-link" href="{{ route('members.index') }}">Member</a>
                            </li>--}}
                            @if (auth()->check())
                                {{--  <li class="nav-item {{ Request::is('settings/profile') ? 'active ' : '' }}">
                                    <a class="nav-link" href="{{ url('/settings/profile') }}">Profil</a>
                                </li>  --}}
                            @endif
                        @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">Daftar</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ url('/settings/password') }}"><i class="fa fa-btn fa-lock"></i> Ubah Password</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="	fa fa-sign-out"></i>
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
                @include('layouts._flash')
            @yield('content')
        </main>
    </div>
    {{--  JS  --}}
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/selectize.min.js') }}"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script src="{{ asset('js/custom.js') }}"></script>
    @yield('scripts')
</body>
</html>